### ISSUE TITLE
Upper case NPM disagrees with style guide

### ISSUE THREAD

**Issue by MikeMcC399** [sclavijosuero/how-to-create-a-cypress-plugin#1]
See https://github.com/npm/cli#faq-on-branding

#### Is it "npm" or "NPM" or "Npm"?

**`npm`** should never be capitalized unless it is being displayed in a location that is customarily all-capitals (ex. titles on `man` pages).

**Comment by sclavijosuero** [comment]
Fixed in v1.0.1 released 8/2/2024
