### ISSUE TITLE
Bad link to blog

### ISSUE THREAD

**Issue by MikeMcC399** [sclavijosuero/how-to-create-a-cypress-plugin#2]
The [README](https://github.com/sclavijosuero/how-to-create-a-cypress-plugin/blob/main/README.md) contains a link to

https://dev.to/sebastianclavijo/the-quirky-guide-to-crafting-and-publishing-your-cypress-npm-plugin-5hbb-temp-slug-1196131

which results in a 404 not found error.

**Comment by sclavijosuero** [comment]
Fixed in v1.0.1 released 8/2/2024
